name: patate_for_kids
channels:
- !!python/unicode
  'defaults'
dependencies:
- pip==9.0.1
- numpy==1.12.0
- pandas==0.19.2
- h5py==2.7.0
- pip:
  - imutils==0.4.5
  - tensorflow==1.1.0
  - keras==2.0.4
