name: patate_for_kids 
channels:
- !!python/unicode
  'defaults'
dependencies:
- python=3.5
- pip==9.0.1
- numpy==1.12.0
- pandas==0.19.2
- pillow==4.0.0
- h5py==2.7.0
- imutils==0.4.5
- pip:
  - tensorflow==1.1.0
  - keras==2.0.4
